In [8]:
import numpy as np
import pandas as pd

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.2.6
Pandas: 2.3.3


In [9]:
import sys

print(sys.executable)

c:\Users\Maryam\AppData\Local\Programs\Python\Python310\python.exe


# Day 3 - NumPy & Pandas Deep Dive

## Objectives
- NumPy Array Operations
- Statistical Analysis
- Data Loading
- Data Cleaning
- Data Merging

In [10]:
# Create random array

arr = np.random.randint(1, 101, 20)

print("Original Array:")
print(arr)

Original Array:
[ 70  91  18  37   5  66  37  78  93   7  34  49  33 100  61  32  36  85
  18  14]


In [11]:
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
minimum = np.min(arr)
maximum = np.max(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)
print("Minimum:", minimum)
print("Maximum:", maximum)

Mean: 48.2
Median: 37.0
Standard Deviation: 29.47303852676205
Minimum: 5
Maximum: 100


In [12]:
matrix = arr.reshape(4,5)

print("4 x 5 Matrix")
print(matrix)

4 x 5 Matrix
[[ 70  91  18  37   5]
 [ 66  37  78  93   7]
 [ 34  49  33 100  61]
 [ 32  36  85  18  14]]


In [13]:
print("First Two Rows")
print(matrix[:2])

First Two Rows
[[70 91 18 37  5]
 [66 37 78 93  7]]


In [14]:
multiplied_matrix = matrix * 2

print("Matrix After Multiplying by 2")
print(multiplied_matrix)

Matrix After Multiplying by 2
[[140 182  36  74  10]
 [132  74 156 186  14]
 [ 68  98  66 200 122]
 [ 64  72 170  36  28]]


In [15]:
with open("../outputs/numpy_results.txt","w") as file:

    file.write("Original Array\n")
    file.write(str(arr))

    file.write("\n\nMean: " + str(mean))
    file.write("\nMedian: " + str(median))
    file.write("\nStd: " + str(std))
    file.write("\nMin: " + str(minimum))
    file.write("\nMax: " + str(maximum))

print("NumPy Results Saved")

NumPy Results Saved


# Dataset Loading

Titanic Dataset is loaded using Pandas.

In [16]:
df = pd.read_csv("../data/titanic.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [17]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


In [18]:
print("Shape of Dataset")
print(df.shape)

Shape of Dataset
(891, 12)


In [19]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [20]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [21]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
missing = pd.DataFrame(
    df.isnull().sum(),
    columns=["Missing Values"]
)

missing

,Missing Values
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [23]:
df["Age"] = df["Age"].fillna(
    df["Age"].mean()
)

In [24]:
df["Embarked"] = df["Embarked"].fillna(
    "Unknown"
)

In [25]:
df["Cabin"] = df["Cabin"].fillna(
    "Not Available"
)

In [26]:
before = df.shape[0]

df = df.drop_duplicates()

after = df.shape[0]

print("Rows Before:", before)
print("Rows After:", after)

Rows Before: 891
Rows After: 891


In [27]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [28]:
df["Age"] = df["Age"].astype(float)

print(df["Age"].dtype)

float64


In [29]:
df.to_csv(
    "../data/cleaned_titanic.csv",
    index=False
)

print("Clean Dataset Saved")

Clean Dataset Saved


# Data Merging

Creating a supplementary dataframe and merging it with Titanic dataset.

In [30]:
class_df = pd.DataFrame({

    "Pclass":[1,2,3],

    "Class_Name":[
        "First Class",
        "Second Class",
        "Third Class"
    ]
})

class_df

,Pclass,Class_Name
0,1,First Class
1,2,Second Class
2,3,Third Class


In [31]:
merged_df = pd.merge(

    df,
    class_df,

    on="Pclass",
    how="left"
)

In [32]:
merged_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Class_Name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Not Available,S,Third Class
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,First Class
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Not Available,S,Third Class
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,First Class
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Not Available,S,Third Class


In [33]:
merged_df.to_csv(
    "../outputs/merged_dataset.csv",
    index=False
)

print("Merged Dataset Saved")

Merged Dataset Saved


In [34]:
with open(
    "../outputs/cleaning_report.txt",
    "w"
) as file:

    file.write("DATA CLEANING REPORT\n")
    file.write("===================\n\n")

    file.write("1. Missing values handled.\n")
    file.write("2. Age column filled using mean.\n")
    file.write("3. Embarked column filled with Unknown.\n")
    file.write("4. Cabin column filled with Not Available.\n")
    file.write("5. Duplicate rows removed.\n")
    file.write("6. Data types verified.\n")

print("Cleaning Report Saved")

Cleaning Report Saved


In [35]:
print("========== DAY 3 COMPLETED ==========")

print("NumPy Practice Completed")
print("Dataset Loaded")
print("Dataset Cleaned")
print("Dataset Merged")

print("All Output Files Generated Successfully")

========== DAY 3 COMPLETED ==========
NumPy Practice Completed
Dataset Loaded
Dataset Cleaned
Dataset Merged
All Output Files Generated Successfully
